version: '3.4'
services:
  discovery:
    build:
      context: discovery
      dockerfile: ./discovery.Dockerfile
    ports:
      - "8761:8761"
  user_app:
    build:
      context: user
      dockerfile: ./user.Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_user?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_user?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - EUREKA_SERVER=http://discovery:8761/eureka
      - SPRING_DATA_REDIS_HOST=redis
    ports:
      - "8081"
    deploy:
      replicas: 3
    depends_on:
      - flatrock-mysql
      - discovery
      - redis
  product_app:
    build:
      context: product
      dockerfile: ./product.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - KAFKA_SERVER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_product?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_product?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - EUREKA_SERVER=http://discovery:8761/eureka
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - "8082"
    deploy:
      replicas: 3
    depends_on:
      - kafka
      - flatrock-mysql
      - discovery
      - redis
      - elasticsearch
#  frontend:
#    build:
#      context: frontend
#      dockerfile: ./frontend.Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - /app/node_modules
#    environment:
#      - NODE_ENV=development
#    command: npm start

  order_app:
    build:
      context: order
      dockerfile: ./order.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - KAFKA_SERVER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_order?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_order?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - EUREKA_SERVER=http://discovery:8761/eureka
    ports:
      - "8083"
    deploy:
      replicas: 2
    depends_on:
      - kafka
      - flatrock-mysql
      - discovery
  delivery_app:
    build:
      context: delivery
      dockerfile: ./delivery.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - KAFKA_SERVER=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_product?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://flatrock-mysql:3306/flatrock_product?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - EUREKA_SERVER=http://discovery:8761/eureka

    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - flatrock-mysql
      - discovery
  notification_app:
    build:
      context: notification
      dockerfile: ./notification.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - KAFKA_SERVER=kafka:9092
      - EUREKA_SERVER=http://discovery:8761/eureka
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - discovery
  gateway_app:
    build:
      context: gateway
      dockerfile: ./gateway.Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - EUREKA_SERVER=http://discovery:8761/eureka
    ports:
      - "5555:5555"
    depends_on:
      - discovery
  kafka:
    image: confluentinc/cp-kafka:7.1.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  flatrock-mysql:
    image: mysql:8.0.29
    volumes:
      - ./docker/config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
      image: docker.elastic.co/kibana/kibana:8.6.2
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
