application:
  cors:
    allowed-origins: '${application.services.user},${application.services.product},${application.services.notification},${application.services.order},${application.services.delivery}'
    allowed-methods: '*'
    allowed-headers: '*'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ODA3NjgyNDA0ZDNiYTljMGFjYzI0ZTg3YjIyMGIxYzI4ZWQ1NTE1MzQ5NzM4ZmZlNjY0ODM3NjE2MzVhNThkMjVkMzRkYzRkOGEwOGQ5YTA4MjkzZWUxMjc0M2EyYmE3YjFlNDU3Nzk1OTcxODZkMDAyODk3ZmMwYTNkMGIzNzA=
        # 24 hours
        token-validity-in-seconds: 86400
        secret:
  client-app:
    name: FlatRock
  topic:
    order-created: order-created-topic
    customer-notification: customer-notification-topic
    seller-notification: seller-notification-topic
    order-canceled: order-canceled-topic
    order-reversal: order-reversal-topic
    reserve-failed: reserve-failed-topic
  services:
    user: "http://flatrock_user:8081/"
    product: "http://flatrock_product:8082/"
    delivery: "http://flatrock_delivery:8084/"
    order: "http://flatrock_order:8083/"
    notification: "http://flatrock_notification:8085/"

spring:
  cloud:
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: localhost:9093
  kafka:
    consumer:
      bootstrap-servers: localhost:9093

  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
  task:
    execution:
      thread-name-prefix: flatrock-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: flatrock-scheduling-
      pool:
        size: 2
